name: main
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
